from tkinter import *
from time import sleep
from sodoku_functions import solve_board
from PIL import ImageTk, Image

root = Tk()
root.title("Sodoku Solver")
root.iconbitmap("C:/Users/Anish/Desktop/Data/Python/Code/Projects/Sodoku Solver/metadata/sodoku_icon.ico")

main_img = ImageTk.PhotoImage(Image.open("C:/Users/Anish/Desktop/Data/Python/Code/Projects/Sodoku Solver/metadata/sodoku_solver_image.png"))
main_label = Label(image=main_img)
main_label.grid(row=0, column=0, rowspan=6)

# Solves Sodoku Board on GUI
def solve():
	board = load_values()
	solve_board(board)
	push_to_board(board)


# Takes values from GUI and creates a nested list to represent the board -> returns board
def load_values():
	# Creates nested list of all values from GUI
	board = [[box_1.get(), box_2.get(), box_3.get(), box_4.get(), box_5.get(), box_6.get(), box_7.get(), box_8.get(), box_9.get()],
			[box_10.get(), box_11.get(), box_12.get(), box_13.get(), box_14.get(), box_15.get(), box_16.get(), box_17.get(), box_18.get()],
			[box_19.get(), box_20.get(), box_21.get(), box_22.get(), box_23.get(), box_24.get(), box_25.get(), box_26.get(), box_27.get()],
			[box_28.get(), box_29.get(), box_30.get(), box_31.get(), box_32.get(), box_33.get(), box_34.get(), box_35.get(), box_36.get()],
			[box_37.get(), box_38.get(), box_39.get(), box_40.get(), box_41.get(), box_42.get(), box_43.get(), box_44.get(), box_45.get()],
			[box_46.get(), box_47.get(), box_48.get(), box_49.get(), box_50.get(), box_51.get(), box_52.get(), box_53.get(), box_54.get()],
			[box_55.get(), box_56.get(), box_57.get(), box_58.get(), box_59.get(), box_60.get(), box_61.get(), box_62.get(), box_63.get()],
			[box_64.get(), box_65.get(), box_66.get(), box_67.get(), box_68.get(), box_69.get(), box_70.get(), box_71.get(), box_72.get()],
			[box_73.get(), box_74.get(), box_75.get(), box_76.get(), box_77.get(), box_78.get(), box_79.get(), box_80.get(), box_81.get()]]
	# Nested list comprehension - replaces all empty values with a 0 and converts all filled values to integers
	board = [[0 if value == '' else int(value) for value in row] for row in board]
	return board
	# add a check incase user inputs a string into the input fields

def push_to_board(board):
	# Place Holder for Fold
	# Clears all existing values on GUI Sodoku Board
	clear()

	# Inserts values stored on nested list - board - onto the GUI Sodoku Board
	box_1.insert(0, board[0][0])
	box_2.insert(0, board[0][1])
	box_3.insert(0, board[0][2])
	box_4.insert(0, board[0][3])
	box_5.insert(0, board[0][4])
	box_6.insert(0, board[0][5])
	box_7.insert(0, board[0][6])
	box_8.insert(0, board[0][7])
	box_9.insert(0, board[0][8])
	box_10.insert(0, board[1][0])
	box_11.insert(0, board[1][1])
	box_12.insert(0, board[1][2])
	box_13.insert(0, board[1][3])
	box_14.insert(0, board[1][4])
	box_15.insert(0, board[1][5])
	box_16.insert(0, board[1][6])
	box_17.insert(0, board[1][7])
	box_18.insert(0, board[1][8])
	box_19.insert(0, board[2][0])
	box_20.insert(0, board[2][1])
	box_21.insert(0, board[2][2])
	box_22.insert(0, board[2][3])
	box_23.insert(0, board[2][4])
	box_24.insert(0, board[2][5])
	box_25.insert(0, board[2][6])
	box_26.insert(0, board[2][7])
	box_27.insert(0, board[2][8])
	box_28.insert(0, board[3][0])
	box_29.insert(0, board[3][1])
	box_30.insert(0, board[3][2])
	box_31.insert(0, board[3][3])
	box_32.insert(0, board[3][4])
	box_33.insert(0, board[3][5])
	box_34.insert(0, board[3][6])
	box_35.insert(0, board[3][7])
	box_36.insert(0, board[3][8])
	box_37.insert(0, board[4][0])
	box_38.insert(0, board[4][1])
	box_39.insert(0, board[4][2])
	box_40.insert(0, board[4][3])
	box_41.insert(0, board[4][4])
	box_42.insert(0, board[4][5])
	box_43.insert(0, board[4][6])
	box_44.insert(0, board[4][7])
	box_45.insert(0, board[4][8])
	box_46.insert(0, board[5][0])
	box_47.insert(0, board[5][1])
	box_48.insert(0, board[5][2])
	box_49.insert(0, board[5][3])
	box_50.insert(0, board[5][4])
	box_51.insert(0, board[5][5])
	box_52.insert(0, board[5][6])
	box_53.insert(0, board[5][7])
	box_54.insert(0, board[5][8])
	box_55.insert(0, board[6][0])
	box_56.insert(0, board[6][1])
	box_57.insert(0, board[6][2])
	box_58.insert(0, board[6][3])
	box_59.insert(0, board[6][4])
	box_60.insert(0, board[6][5])
	box_61.insert(0, board[6][6])
	box_62.insert(0, board[6][7])
	box_63.insert(0, board[6][8])
	box_64.insert(0, board[7][0])
	box_65.insert(0, board[7][1])
	box_66.insert(0, board[7][2])
	box_67.insert(0, board[7][3])
	box_68.insert(0, board[7][4])
	box_69.insert(0, board[7][5])
	box_70.insert(0, board[7][6])
	box_71.insert(0, board[7][7])
	box_72.insert(0, board[7][8])
	box_73.insert(0, board[8][0])
	box_74.insert(0, board[8][1])
	box_75.insert(0, board[8][2])
	box_76.insert(0, board[8][3])
	box_77.insert(0, board[8][4])
	box_78.insert(0, board[8][5])
	box_79.insert(0, board[8][6])
	box_80.insert(0, board[8][7])
	box_81.insert(0, board[8][8])

# Clears all existing values on GUI Sodoku Board
def clear():
	box_1.delete(0, END)
	box_2.delete(0, END)
	box_3.delete(0, END)
	box_4.delete(0, END)
	box_5.delete(0, END)
	box_6.delete(0, END)
	box_7.delete(0, END)
	box_8.delete(0, END)
	box_9.delete(0, END)
	box_10.delete(0, END)
	box_11.delete(0, END)
	box_12.delete(0, END)
	box_13.delete(0, END)
	box_14.delete(0, END)
	box_15.delete(0, END)
	box_16.delete(0, END)
	box_17.delete(0, END)
	box_18.delete(0, END)
	box_19.delete(0, END)
	box_20.delete(0, END)
	box_21.delete(0, END)
	box_22.delete(0, END)
	box_23.delete(0, END)
	box_24.delete(0, END)
	box_25.delete(0, END)
	box_26.delete(0, END)
	box_27.delete(0, END)
	box_28.delete(0, END)
	box_29.delete(0, END)
	box_30.delete(0, END)
	box_31.delete(0, END)
	box_32.delete(0, END)
	box_33.delete(0, END)
	box_34.delete(0, END)
	box_35.delete(0, END)
	box_36.delete(0, END)
	box_37.delete(0, END)
	box_38.delete(0, END)
	box_39.delete(0, END)
	box_40.delete(0, END)
	box_41.delete(0, END)
	box_42.delete(0, END)
	box_43.delete(0, END)
	box_44.delete(0, END)
	box_45.delete(0, END)
	box_46.delete(0, END)
	box_47.delete(0, END)
	box_48.delete(0, END)
	box_49.delete(0, END)
	box_50.delete(0, END)
	box_51.delete(0, END)
	box_52.delete(0, END)
	box_53.delete(0, END)
	box_54.delete(0, END)
	box_55.delete(0, END)
	box_56.delete(0, END)
	box_57.delete(0, END)
	box_58.delete(0, END)
	box_59.delete(0, END)
	box_60.delete(0, END)
	box_61.delete(0, END)
	box_62.delete(0, END)
	box_63.delete(0, END)
	box_64.delete(0, END)
	box_65.delete(0, END)
	box_66.delete(0, END)
	box_67.delete(0, END)
	box_68.delete(0, END)
	box_69.delete(0, END)
	box_70.delete(0, END)
	box_71.delete(0, END)
	box_72.delete(0, END)
	box_73.delete(0, END)
	box_74.delete(0, END)
	box_75.delete(0, END)
	box_76.delete(0, END)
	box_77.delete(0, END)
	box_78.delete(0, END)
	box_79.delete(0, END)
	box_80.delete(0, END)
	box_81.delete(0, END)


# Creates Buttons for on, off, check, exit, clear
button_solve = Button(root, text="Solve", padx=226, pady=16, command=solve)
button_clear = Button(root, text="Clear", padx=226, pady=16, command=clear)
button_exit = Button(root, text="Exit", command=root.quit, padx=230, pady=16)

# Places buttons created in previous block onto GUI using grid system
button_solve.grid(row=6, column=0, columnspan=2)
button_clear.grid(row=7, column=0, columnspan=2)
button_exit.grid(row=8, column=0, columnspan=2)

# Creates 81 input field to represent Sodoku Board
box_1 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_2 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_3 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_4 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_5 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_6 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_7 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_8 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_9 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_10 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_11 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_12 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_13 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_14 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_14 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_15 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_16 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_17 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_18 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_19 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_20 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_21 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_22 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_23 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_24 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_25 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_26 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_27 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_28 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_29 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_30 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_31 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_32 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_33 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_34 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_35 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_36 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_37 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_38 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_39 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_40 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_41 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_42 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_43 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_44 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_45 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_46 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_47 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_48 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_49 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_50 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_51 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_52 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_53 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_54 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_55 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_56 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_57 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_58 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_59 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_60 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_61 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_62 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_63 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_64 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_65 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_66 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_67 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_68 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_69 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_70 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_71 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_72 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_73 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_74 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_75 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_76 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_77 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_78 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_79 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_80 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)
box_81 = Entry(root, font=('Arial',32,'bold'), justify="center", borderwidth=3, width=2)

# Places 81 Sodoku Boxes onto GUI using grid system
box_1.grid(row=0, column=3)
box_2.grid(row=0, column=4)
box_3.grid(row=0, column=5)
box_4.grid(row=0, column=6)
box_5.grid(row=0, column=7)
box_6.grid(row=0, column=8)
box_7.grid(row=0, column=9)
box_8.grid(row=0, column=10)
box_9.grid(row=0, column=11)
box_10.grid(row=1, column=3)
box_11.grid(row=1, column=4)
box_12.grid(row=1, column=5)
box_13.grid(row=1, column=6)
box_14.grid(row=1, column=7)
box_15.grid(row=1, column=8)
box_16.grid(row=1, column=9)
box_17.grid(row=1, column=10)
box_18.grid(row=1, column=11)
box_19.grid(row=2, column=3)
box_20.grid(row=2, column=4)
box_21.grid(row=2, column=5)
box_22.grid(row=2, column=6)
box_23.grid(row=2, column=7)
box_24.grid(row=2, column=8)
box_25.grid(row=2, column=9)
box_26.grid(row=2, column=10)
box_27.grid(row=2, column=11)
box_28.grid(row=3, column=3)
box_29.grid(row=3, column=4)
box_30.grid(row=3, column=5)
box_31.grid(row=3, column=6)
box_32.grid(row=3, column=7)
box_33.grid(row=3, column=8)
box_34.grid(row=3, column=9)
box_35.grid(row=3, column=10)
box_36.grid(row=3, column=11)
box_37.grid(row=4, column=3)
box_38.grid(row=4, column=4)
box_39.grid(row=4, column=5)
box_40.grid(row=4, column=6)
box_41.grid(row=4, column=7)
box_42.grid(row=4, column=8)
box_43.grid(row=4, column=9)
box_44.grid(row=4, column=10)
box_45.grid(row=4, column=11)
box_46.grid(row=5, column=3)
box_47.grid(row=5, column=4)
box_48.grid(row=5, column=5)
box_49.grid(row=5, column=6)
box_50.grid(row=5, column=7)
box_51.grid(row=5, column=8)
box_52.grid(row=5, column=9)
box_53.grid(row=5, column=10)
box_54.grid(row=5, column=11)
box_55.grid(row=6, column=3)
box_56.grid(row=6, column=4)
box_57.grid(row=6, column=5)
box_58.grid(row=6, column=6)
box_59.grid(row=6, column=7)
box_60.grid(row=6, column=8)
box_61.grid(row=6, column=9)
box_62.grid(row=6, column=10)
box_63.grid(row=6, column=11)
box_64.grid(row=7, column=3)
box_65.grid(row=7, column=4)
box_66.grid(row=7, column=5)
box_67.grid(row=7, column=6)
box_68.grid(row=7, column=7)
box_69.grid(row=7, column=8)
box_70.grid(row=7, column=9)
box_71.grid(row=7, column=10)
box_72.grid(row=7, column=11)
box_73.grid(row=8, column=3)
box_74.grid(row=8, column=4)
box_75.grid(row=8, column=5)
box_76.grid(row=8, column=6)
box_77.grid(row=8, column=7)
box_78.grid(row=8, column=8)
box_79.grid(row=8, column=9)
box_80.grid(row=8, column=10)
box_81.grid(row=8, column=11)


root.mainloop()